//SINTAXE BÁSICA DO TYPESCRIPT//SINTAXE BÁSICA DO TYPESCRIPT//SINTAXE BÁSICA DO TYPESCRIPT
//SINTAXE BÁSICA DO TYPESCRIPT//SINTAXE BÁSICA DO TYPESCRIPT//SINTAXE BÁSICA DO TYPESCRIPT
//SINTAXE BÁSICA DO TYPESCRIPT//SINTAXE BÁSICA DO TYPESCRIPT//SINTAXE BÁSICA DO TYPESCRIPT

//DECLARAÇÃO DE VARIÁVEIS
var a = 'a' //Não é mais utilizado
let b = 'b'
const c = 'c'

//DECLARAÇÃO DO TIPO DAS VARIÁVEIS

let d :string = 'b';
let e :number = 2;
let f :boolean = true;

let g: string | number = 2; // TIPO STRING **OU** NUMBER
g = 3;

let h: any = 'Pedro';
h = 3;
h = false;

//SINTAXE BÁSICA DO TYPESCRIPT//SINTAXE BÁSICA DO TYPESCRIPT//SINTAXE BÁSICA DO TYPESCRIPT//
//SINTAXE BÁSICA DO TYPESCRIPT//SINTAXE BÁSICA DO TYPESCRIPT//SINTAXE BÁSICA DO TYPESCRIPT//
//SINTAXE BÁSICA DO TYPESCRIPT//SINTAXE BÁSICA DO TYPESCRIPT//SINTAXE BÁSICA DO TYPESCRIPT//